# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170904_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_book', 'Edit book'),)},
        ),
    ]
